In [1]:
import pandas as pd
import numpy as np

In [2]:
sp500_quotes = pd.read_csv('sp500_quotes_clean_v1.csv')

In [3]:
sp500_quotes

        Unnamed: 0        date  open_price  close_price   volume symbol
0               32  2016-04-01       39.56        40.31  2857844      A
1               33  2016-04-04       40.33        40.01  2958061      A
2               34  2016-04-05       39.73        39.26  1900659      A
3               35  2016-04-06       39.17        40.24  1566612      A
4               36  2016-04-07       39.70        39.47  1373839      A
...            ...         ...         ...          ...      ...    ...
598296     7794326  2020-12-24      159.92       160.72   417444    ZTS
598297     7794327  2020-12-28      161.44       162.39  1522435    ZTS
598298     7794328  2020-12-29      163.21       163.12  1188357    ZTS
598299     7794329  2020-12-30      163.51       164.27  1008988    ZTS
598300     7794330  2020-12-31      164.50       165.50  1292649    ZTS

[598301 rows x 6 columns]

In [4]:
sp500_quotes=sp500_quotes.drop(['Unnamed: 0'], axis=1)

In [5]:
def year_quarter (date):
    quarter=''
    year,month,day=date.split('-')
    if month in ['01', '02', '03']:
        quarter='1'
    elif month in ['04', '05', '06']:
        quarter='2'
    elif month in ['07', '08', '09']:
        quarter='3'
    else:
        quarter='4'
    return year+'Q'+quarter

In [6]:
sp500_quotes['period']=sp500_quotes['date'].apply(lambda x :year_quarter(x))

In [7]:
sp500_quotes['period'].unique()

array(['2016Q2', '2016Q3', '2016Q4', '2017Q1', '2017Q2', '2017Q3',
       '2017Q4', '2018Q1', '2018Q2', '2018Q3', '2018Q4', '2019Q1',
       '2019Q2', '2019Q3', '2019Q4', '2020Q1', '2020Q2', '2020Q3',
       '2020Q4'], dtype=object)

In [8]:
periods=sp500_quotes['period'].unique().tolist()

In [9]:
symbols=sp500_quotes['symbol'].unique().tolist()

In [10]:
sp500_companies= pd.read_csv('sp500_companies.csv')

In [11]:
sp500_companies = sp500_companies.drop(['SUB-INDUSTRY'], axis=1)
cols = []
for i in range(len(sp500_companies.columns)):
    cols.append(sp500_companies.columns[i].lower())
sp500_companies.columns = cols

In [12]:
data=sp500_companies.copy()

In [13]:
missing_companies=['BBWI', 'BF.B', 'BRK.B', 'CTRA', 'OGN', 'WTW']
data=data[~data['symbol'].isin(['BBWI', 'BF.B', 'BRK.B', 'CTRA', 'OGN', 'WTW'])]
data=data.reset_index(drop=True)
data

    symbol                  company                  sector
0        A     Agilent Technologies             Health Care
1      AAL  American Airlines Group             Industrials
2      AAP       Advance Auto Parts  Consumer Discretionary
3     AAPL                    Apple  Information Technology
4     ABBV                   AbbVie             Health Care
..     ...                      ...                     ...
494    YUM              Yum! Brands  Consumer Discretionary
495    ZBH            Zimmer Biomet             Health Care
496   ZBRA       Zebra Technologies  Information Technology
497   ZION            Zions Bancorp              Financials
498    ZTS                   Zoetis             Health Care

[499 rows x 3 columns]

In [14]:
cont=0
for per in range(len(periods)):
    cont+=1
    print(cont)
    period_volume_shares=[]
    period_volume_change=[]
    period_volume_dollars=[]
    period_volume_dollars_change=[]
    period_price_change=[]
    col_weight=periods[per]+'_weight'
    col_vol_shares=periods[per]+'_vol_shares'
    col_vol_shares_change=periods[per]+'_vol_shares_change'
    col_vol_dollars=periods[per]+'_vol_$'
    col_vol_change=periods[per]+'_vol_$_change'
    col_price_change=periods[per]+'_price_change'
    for symbol in symbols:
        data_temp=sp500_quotes[(sp500_quotes['symbol']==symbol) & (sp500_quotes['period']==periods[per])]
        data_temp['money']=data_temp['volume']*(data_temp['open_price']+data_temp['close_price'])/2
        volume_shares=data_temp['volume'].sum()
        volume_dollars=data_temp['money'].sum()
        open_period=data_temp[data_temp['date']==data_temp['date'].min()]['open_price']
        close_period=data_temp[data_temp['date']==data_temp['date'].max()]['close_price']
        price_change=round(100*(list(close_period)[0]-list(open_period)[0])/list(open_period)[0], 3)
        period_volume_shares.append(volume_shares)
        period_volume_dollars.append(volume_dollars)
        period_price_change.append(price_change)
    data[col_weight]= period_volume_dollars/sum(period_volume_dollars)
    data[col_vol_shares]=period_volume_shares
    if cont>1:
        col_prev_volume_shares=periods[per-1]+'_vol_shares'
        data[col_vol_shares_change]=round(100*(data[col_vol_shares]-data[col_prev_volume_shares])/data[col_prev_volume_shares],3)
    data[col_vol_dollars]=period_volume_dollars
    if cont>1:
        col_prev_volume_dollars=periods[per-1]+'_vol_$'
        data[col_vol_change]=round(100*(data[col_vol_dollars]-data[col_prev_volume_dollars])/data[col_prev_volume_dollars],3)
    data[col_price_change]=period_price_change

1

C:\Users\Usuario\AppData\Local\Temp/ipykernel_5104/969954688.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_temp['money']=data_temp['volume']*(data_temp['open_price']+data_temp['close_price'])/2

2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17

C:\Users\Usuario\AppData\Local\Temp/ipykernel_5104/969954688.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  data[col_price_change]=period_price_change

18

C:\Users\Usuario\AppData\Local\Temp/ipykernel_5104/969954688.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  data[col_weight]= period_volume_dollars/sum(period_volume_dollars)
C:\Users\Usuario\AppData\Local\Temp/ipykernel_5104/969954688.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  data[col_vol_shares]=period_volume_shares
C:\Users\Usuario\AppData\Local\Temp/ipykernel_5104/969954688.py:31: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  data[col_vol_shares_change]=round(100*(data[col_vol_shares]-data[col_prev_volume_shares])/data[col_prev_volume_shares],3)
C:\Users\Usuario\AppData\Local\Temp/ipykernel_5104/969954688.py:32: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  data[col_vol_dollars]=period_volume_dollars
C:\Users\Usuario\AppData\Local\Temp/ipykernel_5104/969954688.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  data[col_vol_change]=round(100*(data[col_vol_dollars]-data[col_prev_volume_dollars])/data[col_prev_volume_dollars],3)

19

In [15]:
data

,symbol,company,sector,2016Q2_weight,2016Q2_vol_shares,2016Q2_vol_$,2016Q2_price_change,2016Q3_weight,2016Q3_vol_shares,2016Q3_vol_shares_change,...,2020Q3_vol_shares_change,2020Q3_vol_$,2020Q3_vol_$_change,2020Q3_price_change,2020Q4_weight,2020Q4_vol_shares,2020Q4_vol_shares_change,2020Q4_vol_$,2020Q4_vol_$_change,2020Q4_price_change
0,A,Agilent Technologies,Health Care,0.000869,140281524,6.084121e+09,12.133,0.000830,118778364,-15.329,...,-32.749,8.392700e+09,-20.573,13.556,0.000780,98796117,13.565,1.106780e+10,31.874,16.429
1,AAL,American Airlines Group,Industrials,0.003246,685350162,2.272491e+10,-29.454,0.003095,591804177,-13.649,...,-30.518,5.472012e+10,-33.943,-8.828,0.004914,4911375699,13.454,6.975285e+10,27.472,26.667
2,AAP,Advance Auto Parts,Consumer Discretionary,0.001480,67952248,1.035643e+10,0.956,0.001575,65941792,-2.959,...,-20.187,7.863110e+09,-4.278,7.825,0.000626,57630158,10.837,8.879801e+09,12.930,2.572
3,AAPL,Apple,Information Technology,0.035973,10216634504,2.518075e+11,-12.116,0.036441,9144019672,-10.499,...,17.831,1.219853e+12,69.405,26.873,0.062169,7341985215,-33.118,8.825345e+11,-27.652,12.793
4,ABBV,AbbVie,Health Care,0.004862,558100261,3.403161e+10,9.420,0.004282,441785352,-20.841,...,-33.267,4.172285e+10,-28.522,-11.076,0.003482,516898371,16.413,4.942422e+10,18.458,21.527
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,YUM,Yum! Brands,Consumer Discretionary,0.002157,263672978,1.510069e+10,2.522,0.002489,268424732,1.802,...,-41.037,9.463629e+09,-36.270,4.738,0.000724,100457103,-2.143,1.027632e+10,8.588,17.808
495,ZBH,Zimmer Biomet,Health Care,0.001776,106707042,1.242929e+10,13.012,0.001508,79198215,-25.780,...,-34.625,9.259358e+09,-25.869,13.639,0.000697,67987863,-2.176,9.894502e+09,6.859,12.360
496,ZBRA,Zebra Technologies,Information Technology,0.000410,51095977,2.867655e+09,-26.237,0.000337,37395790,-26.813,...,-24.314,5.146935e+09,-12.291,-1.564,0.000550,23037423,20.148,7.811480e+09,51.770,49.655
497,ZION,Zions Bancorp,Financials,0.000769,203548765,5.383679e+09,4.231,0.000842,199391931,-2.042,...,-46.380,3.319119e+09,-45.111,-13.882,0.000340,130829197,27.055,4.820585e+09,45.237,48.665
498,ZTS,Zoetis,Health Care,0.001595,237548740,1.116547e+10,7.935,0.001567,206268952,-13.168,...,-31.211,1.453658e+10,-18.329,20.453,0.001255,109299381,15.826,1.781338e+10,22.542,-0.439

In [23]:
import math
data.replace([np.inf, - np.inf], np.nan, inplace = True)

In [26]:
data.isna().sum()

symbol                      0
company                     0
sector                      0
2016Q2_weight               0
2016Q2_vol_shares           0
                           ..
2020Q4_vol_shares           0
2020Q4_vol_shares_change    0
2020Q4_vol_$                0
2020Q4_vol_$_change         0
2020Q4_price_change         0
Length: 115, dtype: int64

In [25]:
for column in data.columns:
    data[column] = data[column].fillna(0)

In [ ]:
data.to_csv('sp500_by_company.csv')

In [1]:
import pandas as pd
import numpy as np

In [2]:
sp500_companies = pd.read_csv('sp500_by_company.csv')

In [3]:
sp500_sectors = pd.DataFrame({'sector' : []})

In [4]:
sp500_sectors['sector']=sp500_companies['sector'].unique().tolist()

In [5]:
periods=['2016Q2', '2016Q3', '2016Q4', '2017Q1', '2017Q2', '2017Q3',
       '2017Q4', '2018Q1', '2018Q2', '2018Q3', '2018Q4', '2019Q1',
       '2019Q2', '2019Q3', '2019Q4', '2020Q1', '2020Q2', '2020Q3',
       '2020Q4']

In [6]:
#sectores=['Health Care', 'Industrials']

In [7]:
for per in range(1,len(periods)):
    sector_weight=[]
    money_change=[]
    price_change=[]
    col_weight=periods[per]+'_weight'
    col_vol_change=periods[per]+'_vol_$_change'
    col_price_change=periods[per]+'_price_change'
    for sector in sp500_sectors['sector']:
        sector_temp=sp500_companies[sp500_companies['sector']==sector]
        sector_weight.append(sum(sector_temp[col_weight]))
        money_change.append(sum(sector_temp[col_weight]*sector_temp[col_vol_change]))
        price_change.append(sum(sector_temp[col_weight]*sector_temp[col_price_change]))
    sp500_sectors[col_weight]= sector_weight 
    sp500_sectors[col_vol_change]=money_change
    sp500_sectors[col_price_change]=price_change

In [9]:
sp500_sectors

,sector,2016Q3_weight,2016Q3_vol_$_change,2016Q3_price_change,2016Q4_weight,2016Q4_vol_$_change,2016Q4_price_change,2017Q1_weight,2017Q1_vol_$_change,2017Q1_price_change,...,2020Q1_price_change,2020Q2_weight,2020Q2_vol_$_change,2020Q2_price_change,2020Q3_weight,2020Q3_vol_$_change,2020Q3_price_change,2020Q4_weight,2020Q4_vol_$_change,2020Q4_price_change
0,Health Care,0.122948,-0.127079,0.237526,0.123825,2.021532,-0.659801,0.122064,0.229257,1.083685,...,-1.137196,0.107500,1.417321,2.681965,0.081914,-1.329196,0.426723,0.101264,2.494407,1.231456
1,Industrials,0.106165,15.893606,0.578479,0.103475,1.583617,0.989635,0.105974,0.717151,0.473764,...,-2.971138,0.122143,8.113447,2.824650,0.089892,-1.461985,0.501478,0.093895,0.539996,1.832430
2,Consumer Discretionary,0.141895,-0.759651,0.688838,0.139025,1.771189,-0.129971,0.138709,0.405153,1.266958,...,-1.289976,0.192176,2.727325,11.909150,0.267635,22.336814,15.049771,0.249588,-1.849647,7.947052
3,Information Technology,0.175421,0.788187,2.791724,0.175011,3.134284,1.288765,0.186080,2.080215,2.419925,...,-3.087719,0.236402,-1.730713,8.674526,0.276624,8.485716,5.518078,0.251030,-2.031172,3.079082
4,Consumer Staples,0.079939,2.392591,-0.173693,0.069848,0.173427,-0.160289,0.069974,0.075659,0.309475,...,-0.659439,0.047313,-0.421732,0.543319,0.039649,-0.376691,0.348460,0.040989,0.107263,0.221952
5,Utilities,0.031754,-0.062733,-0.230678,0.028451,0.050597,-0.015731,0.026587,-0.165172,0.178687,...,-0.394710,0.022442,-0.403804,0.152502,0.019109,-0.121252,0.060765,0.020374,0.093496,0.117468
6,Financials,0.112152,-0.787698,1.064506,0.139545,5.919181,3.663706,0.136064,-0.281901,0.108620,...,-3.105007,0.086367,-0.223697,1.911332,0.063971,-1.366472,-0.001360,0.072714,0.933564,2.001029
7,Materials,0.029671,-0.105656,0.076989,0.028918,0.337707,0.206168,0.029944,0.111488,0.071434,...,-0.666878,0.023147,0.516972,0.765788,0.019031,-0.069719,0.264984,0.021371,0.239065,0.383449
8,Real Estate,0.032814,-0.062482,-0.124196,0.030978,0.269869,-0.097266,0.029935,-0.001853,0.081730,...,-0.492657,0.025814,0.105187,0.505071,0.018014,-0.470784,0.006590,0.021280,0.328529,0.169421
9,Energy,0.060421,-0.112325,0.362379,0.053731,0.076323,0.454935,0.056505,0.321173,-0.445882,...,-1.859317,0.031819,-0.131150,1.652250,0.021380,-0.604467,-0.478050,0.026317,0.562892,0.913821
10,Communication Services,0.106819,-0.994095,0.893157,0.107192,1.607560,0.028268,0.098163,-0.718157,0.982171,...,-1.604554,0.104878,0.675647,2.785619,0.102780,0.674237,1.069283,0.101178,-0.078009,1.388265

In [30]:
data.columns.to_series()[np.isinf(data).any()]

TypeError: ufunc 'isinf' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [29]:
data.index[np.isinf(data).any(1)]

TypeError: ufunc 'isinf' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [9]:
sector_temp

,Unnamed: 0,symbol,company,sector,2016Q2_weight,2016Q2_vol_shares,2016Q2_vol_$,2016Q2_price_change,2016Q3_weight,2016Q3_vol_shares,...,2020Q3_vol_shares_change,2020Q3_vol_$,2020Q3_vol_$_change,2020Q3_price_change,2020Q4_weight,2020Q4_vol_shares,2020Q4_vol_shares_change,2020Q4_vol_$,2020Q4_vol_$_change,2020Q4_price_change
1,1,AAL,American Airlines Group,Industrials,0.324647,685350162,2.272491e+10,-29.454,0.309509,591804177,...,-30.518,5.472012e+10,-33.943,-8.828,0.491367,4911375699,13.454,6.975285e+10,27.472,26.667
24,24,ALK,Alaska Air Group,Industrials,0.134068,137599575,9.384652e+09,-28.267,0.087795,89481628,...,-39.314,5.607088e+09,-33.910,-1.479,0.042775,136593204,-8.324,6.072262e+09,8.296,40.200
26,26,ALLE,Allegion,Industrials,0.039065,41274471,2.734512e+09,9.038,0.039209,37335033,...,-6.540,4.555210e+09,-3.268,-3.295,0.035270,46331392,3.487,5.006743e+09,9.912,16.450
30,30,AME,Ametek,Industrials,0.066587,97581177,4.661035e+09,-7.169,0.069215,97545498,...,-31.938,6.129102e+09,-21.404,10.764,0.047589,60235803,-5.594,6.755514e+09,10.220,20.099
39,39,AOS,A. O. Smith,Industrials,0.053732,92715752,3.761154e+09,16.209,0.047028,67389902,...,-33.457,3.315894e+09,-22.738,11.486,0.025764,66268713,0.316,3.657419e+09,10.300,2.813
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
459,459,URI,United Rentals,Industrials,0.116211,125810594,8.134667e+09,11.001,0.135959,118856518,...,-48.135,8.768984e+09,-31.386,16.333,0.080861,55247411,5.336,1.147883e+10,30.903,31.334
467,467,VRSK,Verisk Analytics,Industrials,0.045643,40776571,3.194936e+09,1.808,0.051242,41483832,...,-26.330,8.153402e+09,-14.992,9.502,0.053394,38929826,-12.719,7.579705e+09,-7.036,11.770
473,473,WAB,Wabtec,Industrials,0.058429,52894212,4.089991e+09,-10.535,0.063210,57945985,...,-20.806,4.733195e+09,-9.903,6.800,0.040585,84936367,15.022,5.761271e+09,21.721,17.988
481,481,WM,Waste Management,Industrials,0.123553,143989363,8.648551e+09,12.513,0.136860,139857442,...,-33.843,1.152335e+10,-27.173,6.855,0.075469,91997540,-11.728,1.071328e+10,-7.030,3.484
493,493,XYL,Xylem,Industrials,0.050882,82158015,3.561699e+09,9.867,0.049011,66758166,...,-31.031,4.707427e+09,-18.953,29.356,0.034871,52608579,-13.707,4.950209e+09,5.157,20.462

In [17]:
sum(sector_temp['2016Q3_weight']*sector_temp['2020Q3_price_change']/100)

0.878386488071768

In [ ]:
(data['2016Q3_weight']*data['2016Q3_price_change']/499).sum()

In [30]:
# df=data.groupby(['sector']).agg({'2016Q2_price_change':sum,'2016Q3_price_change':sum})

In [107]:
temp

Empty DataFrame
Columns: [symbol, company, sector, weight, 2016Q2_vol_sum, 2016Q2_price_change, 2016Q3_vol_sum, 2016Q3_vol_change, 2016Q3_price_change, 2016Q4_vol_sum, 2016Q4_vol_change, 2016Q4_price_change, 2017Q1_vol_sum, 2017Q1_vol_change, 2017Q1_price_change, 2017Q2_vol_sum, 2017Q2_vol_change, 2017Q2_price_change, 2017Q3_vol_sum, 2017Q3_vol_change, 2017Q3_price_change, 2017Q4_vol_sum, 2017Q4_vol_change, 2017Q4_price_change, 2018Q1_vol_sum, 2018Q1_vol_change, 2018Q1_price_change, 2018Q2_vol_sum, 2018Q2_vol_change, 2018Q2_price_change, 2018Q3_vol_sum, 2018Q3_vol_change, 2018Q3_price_change, 2018Q4_vol_sum, 2018Q4_vol_change, 2018Q4_price_change, 2019Q1_vol_sum, 2019Q1_vol_change, 2019Q1_price_change, 2019Q2_vol_sum, 2019Q2_vol_change, 2019Q2_price_change, 2019Q3_vol_sum, 2019Q3_vol_change, 2019Q3_price_change, 2019Q4_vol_sum, 2019Q4_vol_change, 2019Q4_price_change, 2020Q1_vol_sum, 2020Q1_vol_change, 2020Q1_price_change, 2020Q2_vol_sum, 2020Q2_vol_change, 2020Q2_price_change, 2020Q3_vol_sum, 2020Q3_vol_change, 2020Q3_price_change, 2020Q4_vol_sum, 2020Q4_vol_change, 2020Q4_price_change]
Index: []

[0 rows x 60 columns]

In [63]:
value=data['2020Q4_price_change']*data['weight']

In [88]:
price_change

7.935

In [84]:
close_period

1262    28.31
Name: close_price, dtype: float64

In [68]:
data.columns

Index(['symbol', 'company', 'sector', 'weight', '2016Q2_vol_sum',
       '2016Q2_price_change', '2016Q3_vol_sum', '2016Q3_vol_change',
       '2016Q3_price_change', '2016Q4_vol_sum', '2016Q4_vol_change',
       '2016Q4_price_change', '2017Q1_vol_sum', '2017Q1_vol_change',
       '2017Q1_price_change', '2017Q2_vol_sum', '2017Q2_vol_change',
       '2017Q2_price_change', '2017Q3_vol_sum', '2017Q3_vol_change',
       '2017Q3_price_change', '2017Q4_vol_sum', '2017Q4_vol_change',
       '2017Q4_price_change', '2018Q1_vol_sum', '2018Q1_vol_change',
       '2018Q1_price_change', '2018Q2_vol_sum', '2018Q2_vol_change',
       '2018Q2_price_change', '2018Q3_vol_sum', '2018Q3_vol_change',
       '2018Q3_price_change', '2018Q4_vol_sum', '2018Q4_vol_change',
       '2018Q4_price_change', '2019Q1_vol_sum', '2019Q1_vol_change',
       '2019Q1_price_change', '2019Q2_vol_sum', '2019Q2_vol_change',
       '2019Q2_price_change', '2019Q3_vol_sum', '2019Q3_vol_change',
       '2019Q3_price_change', '2019Q4_vol_sum', '2019Q4_vol_change',
       '2019Q4_price_change', '2020Q1_vol_sum', '2020Q1_vol_change',
       '2020Q1_price_change', '2020Q2_vol_sum', '2020Q2_vol_change',
       '2020Q2_price_change', '2020Q3_vol_sum', '2020Q3_vol_change',
       '2020Q3_price_change', '2020Q4_vol_sum', '2020Q4_vol_change',
       '2020Q4_price_change'],
      dtype='object')

In [72]:
sectors

                    sector
0              Health Care
1              Industrials
2   Consumer Discretionary
3   Information Technology
4         Consumer Staples
5                Utilities
6               Financials
7                Materials
8              Real Estate
9                   Energy
10  Communication Services

In [67]:
data['sector'].unique().tolist()

['Health Care',
 'Industrials',
 'Consumer Discretionary',
 'Information Technology',
 'Consumer Staples',
 'Utilities',
 'Financials',
 'Materials',
 'Real Estate',
 'Energy',
 'Communication Services']

In [21]:
data.to_csv('sp500_prov_v1.csv')

In [22]:
sp500.groupby(['symbol']).agg({'volume':sum})

              volume
symbol
A         2513003268
AAL      23947348178
AAP       1437270426
AAPL    157062528258
ABBV      9128877954
...              ...
YUM       2868601943
ZBH       1584795651
ZBRA       547625664
ZION      3031697640
ZTS       3010747367

[499 rows x 1 columns]

In [ ]:
sp500_companies= pd.read_csv('sp500_companies.csv')

In [ ]:
sp500_companies

In [ ]:
sp500_companies = sp500_companies.drop(['SUB-INDUSTRY'], axis=1)
cols = []
for i in range(len(sp500_companies.columns)):
    cols.append(sp500_companies.columns[i].lower())
sp500_companies.columns = cols

In [ ]:
data=data.drop(['company_y'],axis=1)
data = data.rename(columns={'company_x':'company'})

In [ ]:
missing_companies=['BBWI', 'BF.B', 'BRK.B', 'CTRA', 'OGN', 'WTW']
data=data[~data['symbol'].isin(['BBWI', 'BF.B', 'BRK.B', 'CTRA', 'OGN', 'WTW'])]
data=data.reset_index(drop=True)
data

In [ ]:
periods=sp500_quotes['period'].unique().tolist()

In [ ]:
symbols=data['symbol'].unique().tolist()